version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rsupport-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminForRSBD@
      MYSQL_DATABASE: rsupport_board
      MYSQL_USER: rsboard_sujin
      MYSQL_PASSWORD: rsboard_sujin333
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
